#!/bin/bash

cd ./testfiles/
X=501
while [ $X -le 516 ]
do
  wget -N  http://www.cs.utexas.edu/~geocklam/CS331/assignment5/input$X.txt
  wget -N http://www.cs.utexas.edu/~geocklam/CS331/assignment5/output$X.txt
  X=$((X+1))
done

cd ..
echo "Now testing files  ... "

./build
cp ./testfiles/input1.txt input1.txt
cp ./testfiles/output1.txt output1.txt
cp ./testfiles/output1_alternative.txt output1_alternative.txt

X=501
while [ $X -le 516 ]
do
  cp ./testfiles/input$X.txt input$X.txt
  cp ./testfiles/output$X.txt output$X.txt
  ./run input$X.txt o$X.txt
  
  
  diff -w o$X.txt output$X.txt > diff$X.txt
  echo "Test case $X: input$X.txt"
  if [ -s "diff$X.txt" ];
  then
  echo -e "${red}Failed"
  else
  echo -e "${green}PASSED"
  rm diff$X.txt
  fi
  
  echo "============================="
  
  rm o$X.txt
  rm output$X.txt
  rm input$X.txt
  X=$((X+1))
  
done
